# Generated by Django 3.0.6 on 2020-05-08 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapi', '0002_auto_20200507_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='URLVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortenerapi.URL')),
            ],
            options={
                'ordering': ['date_visited'],
            },
        ),
    ]
