# Generated by Django 3.0.6 on 2020-05-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapi', '0003_auto_20200508_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='custom_version',
        ),
        migrations.AddField(
            model_name='url',
            name='latest_custom_url',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='CustomURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('parent_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortenerapi.URL')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
