# Generated by Django 3.0.6 on 2020-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapi', '0004_auto_20200508_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='latest_custom_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened_version',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
